# Dockerfile.ingestor

FROM python:3.10-slim

# Set working directory inside the container
WORKDIR /ingestor

# Copy ingestor code and requirements
COPY ingestor/ /ingestor/

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Run the ingestion script
CMD ["python", "main.py"]
