services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - uspowerplant_pgdata:/var/lib/postgresql/data
#      - ./ingestor/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

#  pgadmin:
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
#    ports:
#      - "8081:80"
#    depends_on:
#      - postgres
#    networks:
#      - app-network

  ingestor:
    build:
      context: .
      dockerfile: Dockerfile.ingestor
    depends_on:
      - postgres
    restart: "no"
    networks:
      - app-network

#  backend:
#    build:
#      context: .
#      dockerfile: Dockerfile.backend
#    environment:
#      - DATABASE_URL=postgresql://aiq:aiq@postgres:5432/powerplantsdb
#    depends_on:
#      - postgres
#    ports:
#      - "8000:8000"
#    networks:
#      - app-network
#
#  frontend:
#    build:
#      context: .
#      dockerfile: Dockerfile.frontend
#    ports:
#      - "3000:80"
#    depends_on:
#      - backend
#    networks:2
#      - app-network

volumes:
  uspowerplant_pgdata:

networks:
  app-network:
    name: uspowerplant_app-network
    driver: bridge