import os
from dotenv import load_dotenv

load_dotenv()

AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
AWS_DEFAULT_REGION=os.getenv('AWS_DEFAULT_REGION')

S3_BUCKET = os.getenv('S3_BUCKET')
DEFAULT_FILE_NAME=os.getenv('DEFAULT_FILE_NAME')
DEFAULT_FILE_PATH=os.getenv('DEFAULT_FILE_PATH')

POSTGRES_HOST = "postgres"
POSTGRES_PORT = 5432
POSTGRES_USER = os.getenv("POSTGRES_USER")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")
POSTGRES_DB = os.getenv("POSTGRES_DB")

DATABASE_URL = (
    f"postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}"
    f"@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}"
)
print("dbURL" , DATABASE_URL);

